services:
  ducky.bot.v1:
    build: .
    image: ducky.bot.v1
    container_name: ducky.bot.v1
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ducky-data:/app/data
    restart: always

volumes:
  ducky-data: